In [1]:
import cv2
import numpy as np
#method only works when text is large enough
img=cv2.imread('dotted2.jpg')

kernel1 = np.ones((3,5),np.uint8)
kernel2 = np.ones((9,9),np.uint8)

imgGray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgBW=cv2.threshold(imgGray, 230, 255, cv2.THRESH_BINARY_INV)[1]

img1=cv2.erode(imgBW, kernel1, iterations=1)
img2=cv2.dilate(img1, kernel2, iterations=3)
img3 = cv2.bitwise_and(imgBW,img2)
img3= cv2.bitwise_not(img3)
img4 = cv2.bitwise_and(imgBW,imgBW,mask=img3)
imgLines= cv2.HoughLinesP(img4,15,np.pi/180,10, minLineLength = 440, maxLineGap = 1500)

cv2.imshow('Final Image with dotted Lines detected', img4)
cv2.waitKey(0)

for i in range(len(imgLines)):
    for x1,y1,x2,y2 in imgLines[i]:
        cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imshow('Final Image with dotted Lines detected', img)
cv2.waitKey(0)

-1

In [6]:
import cv2
import numpy as np

def filterLines(lines):
    ret=[]
    for i in lines:
        x1, y1, x2, y2 = i[0]
        flag=False
        for j in ret:
            dx1, dy1, dx2, dy2 = j[0]
            if abs(x1-dx1)+abs(y1-dy1)+abs(x2-dx2)+abs(y2-dy2) < 50:
                flag=True
                break
        if not flag:
            ret.append(i)
    return ret


img = cv2.imread('dotted4.jpg')
# cv2.imshow("Result Image", img)
# cv2.waitKey(0)
# Convert the image to gray-scale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Find the edges in the image using canny detector
edges = cv2.Canny(gray, 50, 200)
# Detect points that form a line
lines = cv2.HoughLinesP(edges, 1, np.pi/180, 100, minLineLength=100, maxLineGap=80)
# print(len(lines))
print(len(filterLines(lines)))
# Draw lines on the image
for line in filterLines(lines):
    x1, y1, x2, y2 = line[0]
    temp=np.sum(img==255)
    cv2.line(img, (x1, y1), (x2, y2), (255, 0, 0), 5)
    bba=(abs(x1-x2)+abs(y1-y2))
    print((np.sum(img==255)-temp)/bba)

# Show result
cv2.imshow("Result Image", img)
cv2.waitKey(0)


10
-1.536231884057971
-3.6556603773584904
-3.808
-1.1518151815181519
-3.988919667590028
-4.916
-1.5
-7.666666666666667
-3.59375
-0.7933884297520661


-1

In [103]:
import cv2

#Read gray image
img = cv2.imread("dotted2.jpg",0)

#Create default parametrization LSD
lsd = cv2.createLineSegmentDetector(0)

# print(img)

#Detect lines in the image
lines = lsd.detect(img)[0] #Position 0 of the returned tuple are the detected lines
print(len(lines))
#Draw detected lines in the image
drawn_img = lsd.drawSegments(img,lines)

#Show image
cv2.imshow("LSD",drawn_img )
cv2.waitKey(0)

109


-1

In [117]:
import cv2 as cv
src = cv.imread("dotted3.jpg", cv.IMREAD_GRAYSCALE)
dst = cv.Canny(src, 50, 200, None, 3)
linesP = cv.HoughLinesP(dst, 1, np.pi / 180, 50, None, 50, 10)
for i in range(len(imgLines)):
    for x1,y1,x2,y2 in imgLines[i]:
        cv2.line(src,(x1,y1),(x2,y2),(0,255,0),4)
print(linesP)
cv2.imshow('Final Image with dotted Lines detected', src)
cv2.waitKey(0)

[[[236  63 656  63]]

 [[234  58 657  58]]

 [[116 409 116  78]]

 [[121 411 121  76]]

 [[234 101 551 101]]

 [[234 105 545 105]]

 [[147 444 147 121]]

 [[146 133 146  17]]

 [[545 104 661 104]]]


-1